CREATE DATABASE IF NOT EXISTS basketball_bot CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE basketball_bot;

CREATE TABLE IF NOT EXISTS active_games (
  chat_id BIGINT PRIMARY KEY,
  state_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game_history (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  chat_id BIGINT NOT NULL,
  mode INT NOT NULL DEFAULT 50,
  players_count INT NOT NULL,
  result_json LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
